version: '3.8'

services:
  pcsaerospace-uh1h:
    container_name: uh1h.pcsaerospace.com
    image: pcsaerospace:uh1h-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www/html
